[global]

port = ":8890"

logdir = "/export/publish/"

[mhxzx_dev]

game = "mhxzx"

user = "doumaoxin"

host = "192.168.137.132"

secrets = "/etc/rsyncd.scrt"

path = "/home/mhxzx/beegoDemo"

[game_redist]

game = "zzbq"

user = "frostland"

host = "127.0.0.1"

secrets = "/etc/rsyncd_client.secrets"

path = "/home/frostland/frostland_package"
